<#
    .NOTES
    --------------------------------------------------------------------------------
     Form Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2019 v5.6.167
     Generated on:       	  11/1/2019 3:52 PM
     Generated by:      	  Alan Newingham
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2019
#>

function Show-ProfileBackup {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formProfileBackup011ByAl = New-Object 'System.Windows.Forms.Form'
	$statusbar1 = New-Object 'System.Windows.Forms.StatusBar'
	$buttonCopyToClipboard = New-Object 'System.Windows.Forms.Button'
	$labelLog = New-Object 'System.Windows.Forms.Label'
	$labelCheckDirectoryYouWan = New-Object 'System.Windows.Forms.Label'
	$Info = New-Object 'System.Windows.Forms.GroupBox'
	$labelenvUserName = New-Object 'System.Windows.Forms.Label'
	$labelVer = New-Object 'System.Windows.Forms.Label'
	$labelOSInstallDate = New-Object 'System.Windows.Forms.Label'
	$labeloperatingSystemID = New-Object 'System.Windows.Forms.Label'
	$labelenvCOMPUTERNAME = New-Object 'System.Windows.Forms.Label'
	$labeloperatingSystemNumbe = New-Object 'System.Windows.Forms.Label'
	$labelAuthenticatedUser = New-Object 'System.Windows.Forms.Label'
	$labelInstDate = New-Object 'System.Windows.Forms.Label'
	$labelWindowsUser = New-Object 'System.Windows.Forms.Label'
	$label1 = New-Object 'System.Windows.Forms.Label'
	$labelDeviceName = New-Object 'System.Windows.Forms.Label'
	$buttonPrograms = New-Object 'System.Windows.Forms.Button'
	$progressbar1 = New-Object 'System.Windows.Forms.ProgressBar'
	$groupbox3 = New-Object 'System.Windows.Forms.GroupBox'
	$checkboxSelectAll = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxOneNote2016 = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxStickyNotes = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxAdobeSignatureSecuri = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxOfficeRibbonAndQAT = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxOutlookSettings = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxOutlookSignature = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxOneDrive = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxCustomDirectory = New-Object 'System.Windows.Forms.CheckBox'
	$textbox7 = New-Object 'System.Windows.Forms.TextBox'
	$checkboxQuickparts = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxBrowsers = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxVideos = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxPictures = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxDocuments = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxDownloads = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxDesktop = New-Object 'System.Windows.Forms.CheckBox'
	$buttonInventory = New-Object 'System.Windows.Forms.Button'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$textbox2 = New-Object 'System.Windows.Forms.TextBox'
	$labelFromLocation = New-Object 'System.Windows.Forms.Label'
	$labelToLocation = New-Object 'System.Windows.Forms.Label'
	$buttonBACKUP = New-Object 'System.Windows.Forms.Button'
	$buttonPrinters = New-Object 'System.Windows.Forms.Button'
	$richtextbox1 = New-Object 'System.Windows.Forms.RichTextBox'
	$tooltip1 = New-Object 'System.Windows.Forms.ToolTip'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formProfileBackup011ByAl_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	
	#Begin Region - Automatic System Information Gathering
	#shortened my information gathering script to this as it was taking the script too long to load on startup. 
	$operatingSystemNumber = (Get-WmiObject -class Win32_OperatingSystem).Caption
	$operatingSystemID = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId
	$CurrentUserName = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
	[string]$ComputerName = $env:computername
	$Computer = $ComputerName
	$LoggedOnUser = (Get-WmiObject win32_computersystem -ComputerName $Computer).Username
	$InstDate = (Get-CimInstance Win32_OperatingSystem).InstallDate
	#End Region - Automatic System Information Gathering
	
	# Setting up Speech
	# Need to load the System.Speech assembly
	Add-Type -AssemblyName System.speech
	
	# Now we create the SpeechSynthesizer object.
	$speak = New-Object System.Speech.Synthesis.SpeechSynthesizer
	
	# Setting voice
	$speak.SelectVoice('Microsoft Zira Desktop')
	
	function Get-Printers
	{
		$source = $texbox1.Text
		$dest = $textbox2.Text
		$cn = $env:Computername
		#================Code Start===================
		$path = "$dest\Logs\$cn"
		$Printservers = $env:computername
		
		
		
		# Create new Excel workbook
		$Excel = New-Object -ComObject Excel.Application
		$Excel.Visible = $True
		$Excel = $Excel.Workbooks.Add()
		$Sheet = $Excel.Worksheets.Item(1)
		$Sheet.Name = "Printer Inventory"
		#======================================================
		$Sheet.Cells.Item(1, 1) = "Print Server"
		$Sheet.Cells.Item(1, 2) = "Printer Name"
		$Sheet.Cells.Item(1, 3) = "Port Name"
		$Sheet.Cells.Item(1, 4) = "Share Name"
		$Sheet.Cells.Item(1, 5) = "Driver Name"
		$Sheet.Cells.Item(1, 6) = "Driver Version"
		$Sheet.Cells.Item(1, 7) = "Driver"
		$Sheet.Cells.Item(1, 8) = "Location"
		$Sheet.Cells.Item(1, 9) = "Comment"
		$Sheet.Cells.Item(1, 10) = "Shared"
		#=======================================================
		$intRow = 2
		$WorkBook = $Sheet.UsedRange
		$WorkBook.Interior.ColorIndex = 33
		$WorkBook.Font.ColorIndex = 1
		$WorkBook.Font.Bold = $True
		#=======================================================
		
		
		ForEach ($Printserver in $Printservers)
		{
			$Printers = Get-WmiObject Win32_Printer -ComputerName $Printserver
			ForEach ($Printer in $Printers)
			{
				if ($Printer.Name -notlike "Microsoft XPS*")
				{
					$Sheet.Cells.Item($intRow, 1) = $Printserver
					$Sheet.Cells.Item($intRow, 2) = $Printer.Name
					
					If ($Printer.PortName -notlike "*\*")
					{
						$Ports = Get-WmiObject Win32_TcpIpPrinterPort -Filter "name = '$($Printer.Portname)'" -ComputerName $Printserver
						ForEach ($Port in $Ports)
						{
							$Sheet.Cells.Item($intRow, 3) = $Port.HostAddress
						}
					}
					
					$Sheet.Cells.Item($intRow, 4) = $Printer.ShareName
					$Sheet.Cells.Item($intRow, 5) = $Printer.DriverName
					
					####################       
					$Drivers = Get-WmiObject Win32_PrinterDriver -Filter "__path like '%$($Printer.DriverName)%'" -ComputerName $Printserver
					ForEach ($Driver in $Drivers)
					{
						$Drive = $Driver.DriverPath.Substring(0, 1)
						$Sheet.Cells.Item($intRow, 6) = (Get-ItemProperty ($Driver.DriverPath.Replace("$Drive`:", "\\$PrintServer\$Drive`$"))).VersionInfo.ProductVersion
						$Sheet.Cells.Item($intRow, 7) = Split-Path $Driver.DriverPath -Leaf
					}
					####################
					
					$Sheet.Cells.Item($intRow, 8) = $Printer.Location
					$Sheet.Cells.Item($intRow, 9) = $Printer.Comment
					$Sheet.Cells.Item($intRow, 10) = $Printer.Shared
					$intRow++
				}
			}
			$WorkBook.EntireColumn.AutoFit() | Out-Null
		}
		
		
		$intRow++
		$Sheet.Cells.Item($intRow, 1) = "Printer inventory completed - @Alan Newingham@"
		$Sheet.Cells.Item($intRow, 1).Font.Bold = $True
		$Sheet.Cells.Item($intRow, 1).Interior.ColorIndex = 33
		$Sheet.Cells.Item($intRow, 2).Interior.ColorIndex = 33
		
		$service = "PrinterLog_{0:yyyyMMdd-HHmm}.xlsx" -f (Get-Date)
		$output = $Path
		$output += $service
		$richtextbox1.Text += "`n The location of the printers Excel file is: $output"
		$Excel.SaveAs($output)
		
		#================Code End=====================
	}
	
	
	
	function Get-ApplicationEvents
	{
		#I wanted a good method to quickly backup event logs.
		$source = $Texbox1.Text
		$dest = $Textbox2.Text
		$cn = $env:Computername
		$path = "$dest\Desktop\$cn\Logs\"
		#Eventlogs
		
		# Config
		$logFileName = "Application" # Add Name of the Logfile (System, Application, etc)
			
		# do not edit
		$exportFileName = $logFileName + ".evt"
		$logFile = Get-WmiObject Win32_NTEventlogFile | Where-Object { $_.logfilename -eq $logFileName }
		$logFile.backupeventlog($path + $exportFileName)
		Remove-Variable source
		Remove-Variable cn
		Remove-Variable dest
		Remove-Variable path
		Remove-Variable exportFileName
		Remove-Variable logFileName
		Remove-Variable logFile
	}
	
	function Get-SystemEvents
	{
		#I wanted a good method to quickly backup event logs.
		$source = $Texbox1.Text
		$dest = $Textbox2.Text
		$cn = $env:Computername
		$path = "$dest\Desktop\$cn\Logs\"
		#Eventlogs
		
		# Config
		$logFileName = "System" # Add Name of the Logfile (System, Application, etc)
		
		# do not edit
		$exportFileName = $logFileName + ".evt"
		$logFile = Get-WmiObject Win32_NTEventlogFile | Where-Object { $_.logfilename -eq $logFileName }
		$logFile.backupeventlog($path + $exportFileName)
		Remove-Variable source
		Remove-Variable cn
		Remove-Variable dest
		Remove-Variable path
		Remove-Variable exportFileName
		Remove-Variable logFileName
		Remove-Variable logFile
	}
	
	function Get-Excel
	{
		$source = $Texbox1.Text
		$dest = $Textbox2.Text
		$cn = $env:Computername
		$now = get-date
		$path = "$dest\Desktop\$cn\Logs\"
		
		cd $path;
		
		$csvs = Get-ChildItem .\* -Include *.csv
		$y = $csvs.Count
		$richtextbox1.Text += "`n`nI have detected the following CSV files: ($y)`n"
		$speak.Speak("`nThere are a total of $y C S V files. Just a moment. Consolidating data.")
		foreach ($csv in $csvs)
		{
			$richtextbox1.Text += $csv.Name
			$richtextbox1.Text += "`n`n"
		}
		$outputfilename = "$dest\Desktop\$cn\Logs\combined-data.xlsx"
		$speak.Speak("Crating $outputfilename.")
		$richtextbox1.Text += "`nCreating: $outputfilename`n"
		
		$excelapp = new-object -comobject Excel.Application
		$excelapp.sheetsInNewWorkbook = $csvs.Count
		$xlsx = $excelapp.Workbooks.Add()
		$sheet = 1
		
		foreach ($csv in $csvs)
		{
			$row = 1
			$column = 1
			$worksheet = $xlsx.Worksheets.Item($sheet)
			$worksheet.Name = $csv.Name
			$file = (Get-Content $csv)
			foreach ($line in $file)
			{
				$linecontents = $line -split ',(?!\s*\w+")'
				foreach ($cell in $linecontents)
				{
					$worksheet.Cells.Item($row, $column) = $cell
					$column++
				}
				$column = 1
				$row++
			}
			$sheet++
		}
		$output = "$dest\Desktop\$cn\Logs\Combined-data.xlsx"
		$xlsx.SaveAs($output)
		$excelapp.quit()
	
		Remove-Variable outputfilename
		Remove-Variable sheet
		Remove-Variable csvs
		Remove-Variable linecontents
		Remove-Variable worksheet
		Remove-Variable file
		Remove-Variable line
		Remove-Variable csv
		Remove-Variable column
		Remove-Variable row
		Remove-Variable path
		Remove-Variable output
	}
	
	function Get-PSInventory
	{
		
		$source = $texbox1.Text
		$dest = $textbox2.Text
		$Path = $textbox2.Text
		$cn = $env:Computername
		$el_c = @()
		$now = get-date
		Set-Variable -Name EventAgeDays -Value 7
		$startdate = $now.adddays(-$EventAgeDays)
		
		$Path = $Path + "\Desktop\" + $cn + "\Logs\"
		If (!(test-path $path))
		{
			New-Item -ItemType Directory -Force -Path $path
		}
		#This is setup as an array for multiple systems, dumbed down this portion of the script to flow correctly.
		Set-Variable -Name ExportFolder -Value "$Path\Desktop\$cn\Logs\$now"
		$ExportFile = $ExportFolder + "el" + $now.ToString("yyyy-MM-dd---hh-mm-ss") + ".csv"
		Write-Host = "PSDrive"
		$richtextbox1.Text += "Gathering Powershell Drive Mappings.`n"
		Get-PSDrive | Export-CSV "$Path\PSDrive.csv" -NoTypeInfo
		Write-Host = "Logical Drives"
		$richtextbox1.Text += "Gathering Logical Drive Mappings.`n"
		Get-CimInstance -Class Win32_LogicalDisk | Export-CSV "$Path\LogicalDisk.csv" -NoTypeInfo
		Write-Host = "Network Drives"
		$richtextbox1.Text += "Gathering Network Drive Mappings`n"
		Get-CimInstance -Class Win32_NetworkConnection | Export-CSV "$Path\NetworkConnectedDrives.csv" -NoTypeInfo
		Write-Host = "Connected Drives"
		$richtextbox1.Text += "Gathering Connected Drive Mappings.`n"
		Get-PSDrive -PSProvider FileSystem | Export-CSV "$Path\ConnectedDrives.csv" -NoTypeInfo
		Write-Host = "OSInfo"
		$richtextbox1.Text += "Gathering OS Info.`n"
		Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version, ServicePackMajorVersion, OSArchitecture, CSName, WindowsDirectory | Export-CSV "$Path\OSInfo.csv" -NoTypeInfo
		Write-Host = "BIOS Settings"
		$richtextbox1.Text += "Gathering BIOS info.`n"
		Get-Ciminstance -classname win32_bios -computername $env:COMPUTERNAME | format-list serialnumber | Export-CSV "$Path\BIOS.csv" -NoTypeInfo
		Write-Host = "IPConfig"
		$richtextbox1.Text += "Gathering IP Config Info.`n"
		Get-NetIPConfiguration -Detailed | Export-CSV "$Path\IPConfig.csv" -NoTypeInfo
		Write-Host = "Local Admins"
		$richtextbox1.Text += "Gathering Local Admin Settings.`n"
		Get-LocalGroupMember -Group "Administrators" | Export-CSV "$Path\AdminAccounts.csv" -NoTypeInfo
		Write-Host = "Comptuername"
		$richtextbox1.Text += "Gathering Computer Name.`n"
		$obj = New-Object psobject -Property @{ ComputerName = $env:COMPUTERNAME }
		$obj | Export-Csv -Path $Path\ComputerName.csv -Encoding UTF8 -NoTypeInformation
		Write-Host = "Firewalls"
		$richtextbox1.Text += "Gathering Firewall Settings.`n"
		Write-Host = "Application Events"
		$logfile = Get-WmiObject -Class win32_NTEventlogFile  -Filter "logFileName='Application'"
		$logfile.ClearEventlog('$dest\Desktop\$cn\Logs\%computername%_Application_Logs.evt')
		Write-Host = "System Events"
		$logfile = Get-WmiObject -Class win32_NTEventlogFile  -Filter "logFileName='System'"
		$logfile.ClearEventlog('$dest\Desktop\$cn\Logs\%computername%_System_Logs.evt')
		Write-Host = "Installed Apps"
		$richtextbox1.Text += "Gathering Installed Applications.`n"
		Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Export-CSV "$Path\InstalledApplications.csv" -NoTypeInfo
		Write-Host = "Processes"
		$richtextbox1.Text += "Gathering Current Processes.`n"
		Get-Process | Export-CSV "$Path\Processes.csv" -NoTypeInfo
		Write-Host = "Service"
		$richtextbox1.Text += "Gathering System Services.`n"
		Get-Service | Export-CSV "$Path\Services.csv" -NoTypeInfo
		$richtextbox1.Text += "Consolidating to one Excel File`n"
		Get-Excel
		#More housekeeping
		$richtextbox1.Text += "Deleting all other data that is not needed anymore.`n"
		$deleteallotherdatanow = "$dest\Desktop\$cn\Logs\*"
		Remove-Item -Recurse -Path $deleteallotherdatanow -Exclude Combined-data.xlsx -Force
		$deleteallotherdatanowbutnotthis = "$dest\Desktop\$cn\Logs"
		#Let us copy this file to a better spot. 
		Copy-Item "$deleteallotherdatanowbutnotthis\Combined-data.xlsx" -Destination "$dest\Logs\$cn"
		Copy-Item "$deleteallotherdatanowbutnotthis\%computername%_System_Logs.evt" -Destination "$dest\Logs\$cn"
		Copy-Item "$deleteallotherdatanowbutnotthis\%computername%_Application_Logs.evt" -Destination "$dest\Logs\$cn"
		#Time to clean up this mess.
		Remove-Variable ExportFile
		Remove-Variable ExportFolder
		Remove-Variable now
		Remove-Variable cn
		Remove-Variable dest
		Remove-Variable source
		Remove-Variable deleteallotherdatanow
	}
	
	
	function Get-Inventory
	{
		$InventoryScript = cmd /c "net use"
		$InventoryScript += cmd /c "WMIC OS LIST BRIEF"
		$InventoryScript += cmd /c "WMIC BIOS get serialnumber"
		$InventoryScript += cmd /c "ipconfig /all"
		$InventoryScript += cmd /c 'net localgroup "Administrators"'
		$InventoryScript += cmd /c "WMIC OS GET csname"
		$InventoryScript += cmd /c 'netsh advfirewall export "$textbox2.Text\firwallpolicy.wfw"'
		$InventoryScript += cmd /c "WEVTUtil query-events System /count:500 /rd:true /format:text"
		$InventoryScript | Out-GridView
	}
	function listUsers
	{
		$userFolders = Get-ChildItem -path c:\users | Select-Object Name
		[array]$userFolders = Get-ChildItem -path C:\Users | Select-Object Name
		ForEach ($Item in $userFolders) { $richtextbox1.Items.Add($Item.Name) }
	}
	
	
	function backupDirectory
	{
		$beginning = Get-Date
		$source = $textbox1.Text
		$dest = $textbox2.Text
		$richtextbox1.Text += "Log Start time: $beginning"
		$richtextbox1.Text += "`n"
		$richtextbox1.Text += "`nInitializing Backup Procedure...`n"
		$richtextbox1.Text += "####################################################"
		$richtextbox1.Text += "`n`nPlease check the log file for verification of file transfers. Located: $source\desktop\backuplog.txt.`n`n"
		$richtextbox1.Text += "####################################################"
		$speak.Speak("Initializing backup Procedure. Please wait a moment while I count the directories and files.")
		$becauseAricIsAB = "{0:N2} GB" -f ((Get-ChildItem $source -Recurse | Measure-Object -Property Length -Sum -ErrorAction Stop).Sum / 1GB)
		$recursiveObjectCount = Get-ChildItem -path $source -Recurse | Measure-Object | %{ $_.Count }
		$recursiveObjectCountDirectory = Get-ChildItem -path $source -Recurse -Directory | Measure-Object | %{ $_.Count }
		$recursiveObjectCountFile = Get-ChildItem -path $source -Recurse -File | Measure-Object | %{ $_.Count }
		$speak.Speak("There are a total of $recursiveObjectCount objects in this profile. With a size of $becauseAricIsAB")
		$richtextbox1.Text += "`nThere are a total of $recursiveObjectCount objects in this profile. With a size of $becauseAricIsAB."
		$richtextbox1.Text += "`nThere are a total of $recursiveObjectCountDirectory directories, and $recursiveObjectCountFile files in this profile. "
		$speak.Speak("This will take some time.")
		$richtextbox1.Text += "`n`nWe are checking that the source path is valid. "
		$richtextbox1.Text += "`nIf not you will receive an error message."
		$richtextbox1.Text += "`n#############`n"
		If (Test-Path $source)
		{
			If ($checkboxDesktop.Checked)
			{
				$ProgressBar1.Value = "15"
				$speak.Speak("`nBacking up the Desktop Directory")
				$richtextbox1.Text += "`nInitializing Desktop Directory Backup."
				$desktopDirectory = "{0:N2} GB" -f ((Get-ChildItem $source\Desktop | Measure-Object Length -s).sum / 1Gb)
				$richtextbox1.Text += "`nThe Desktop Directory is $desktopDirectory."
				Robocopy $source\Desktop $dest\Desktop *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$desktopDirectory2 = "{0:N2} GB" -f ((Get-ChildItem $dest\Desktop | Measure-Object Length -s).sum / 1Gb)
				if ($desktopDirectory -eq $desktopDirectory2)
				{
					$richtextbox1.Text += "`nDesktop Directory Completed Backing Up."
					$speak.Speak("The Desktop Directory Completed Backing Up. Continuing backup.")
					$richtextbox1.Text += "`n#############`n"
					$ProgressBar1.Value = "30"
				}
					else
					{
						$speak.Speak("Source and Destination Directories Do Not Match, Please Check Logs!")
						$result = [System.Windows.Forms.MessageBox]::Show('Desktop Source and Destination Directories Do Not Match, Please Check Logs!', 'Warning', 'YesNo', 'Warning')
						$result
					}
			}
			If ($checkboxDocuments.Checked)
			{
				$richtextbox1.Text += "`nInitializing Documents Directory Backup."
				$speak.Speak("Backing up the Documents Directory")
				$documentsDirectory = "{0:N2} GB" -f ((Get-ChildItem $source\Documents | Measure-Object Length -s).sum / 1Gb)
				$richtextbox1.Text += "`nThe Documents Directory is $documentsDirectory."
				Robocopy $source\Documents $dest\Documents *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$documentsDirectory2 = "{0:N2} GB" -f ((Get-ChildItem $dest\Documents | Measure-Object Length -s).sum / 1Gb)
				if ($documentsDirectory -eq $documentsDirectory2)
				{
					$richtextbox1.Text += "`nDocuments Directory Completed Backing Up."
					$speak.Speak("The Documents Directory Completed Backing Up. Continuing backup.")
					$richtextbox1.Text += "`n#############`n"
					$ProgressBar1.Value = "45"
				}
					else
					{
						$speak.Speak("Source and Destination Directories Do Not Match, Please Check Logs!")
						$result = [System.Windows.Forms.MessageBox]::Show('Documents Source and Destination Directories Do Not Match, Please Check Logs!', 'Warning', 'YesNo', 'Warning')
						$result
					}
			}
			If ($checkboxDownloads.Checked)
			{
				$richtextbox1.Text += "`nInitializing Downloads Directory Backup."
				$speak.Speak("Backing up the Downloads Directory")
				$downloadsDirectory = "{0:N2} GB" -f ((Get-ChildItem $source\Downloads | Measure-Object Length -s).sum / 1Gb)
				$richtextbox1.Text += "`nThe Downloads Directory is $downloadsDirectory."
				Robocopy $source\Downloads $dest\Downloads *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$downloadsDirectory2 = "{0:N2} GB" -f ((Get-ChildItem $dest\Downloads| Measure-Object Length -s).sum / 1Gb)
				if ($downloadsDirectory -eq $downloadsDirectory2)
				{
					$richtextbox1.Text += "`nDownloads Directory Completed Backing Up."
					$speak.Speak("The Downloads Directory Completed Backing Up. Continuing backup.")
					$richtextbox1.Text += "`n#############`n"
					$ProgressBar1.Value = "57"
				}
					else
					{
						$speak.Speak("Source and Destination Directories Do Not Match, Please Check Logs!")
						$result = [System.Windows.Forms.MessageBox]::Show('Downloads Source and Destination Directories Do Not Match, Please Check Logs!', 'Warning', 'YesNo', 'Warning')
						$result
					}
			}
			If ($checkboxBrowsers.Checked)
			{
				$richtextbox1.Text += "`nInitializing Browser data backup. We are attempting closing the browsers now."
				$speak.Speak("Backing up the browser data. We are closing the browsers now.")
				
				#Find and close Firefox browser
				$firefox = Get-Process firefox -ErrorAction SilentlyContinue
				if ($firefox)
				{
					$speak.Speak("Firefox was found running, closing the application gracefully.")
					# try gracefully first
					$firefox.CloseMainWindow()
					# kill after five seconds
					Sleep 5
					if (!$firefox.HasExited)
					{
						$speak.Speak("Firefox did not shut down gracefully, forcing the application closed now.")
						$firefox | Stop-Process -Force
					}
				}
				
				
				#Find and close Chrome browser
				$chrome = Get-Process chrome -ErrorAction SilentlyContinue
				if ($chrome)
				{
					$speak.Speak("Chrome was found running, closing the application gracefully.")
					# try gracefully first
					$chrome.CloseMainWindow()
					# kill after five seconds
					Sleep 5
					if (!$chrome.HasExited)
					{
						$speak.Speak("Chrome was found running, closing.")
						$chrome | Stop-Process -Force
					}
				}
				
				
				#Find and close Internet Explorer
				$ie = Get-Process iexplore -ErrorAction SilentlyContinue
				if ($ie)
				{
					$speak.Speak("eye E was found running, closing the application gracefully.")
					# try gracefully first
					$ie.CloseMainWindow()
					# kill after five seconds
					Sleep 5
					if (!$ie.HasExited)
					{
						$speak.Speak("eye E was found running, closing.")
						$ie | Stop-Process -Force
					}
				}
				
				
				#Find and close Opera Explorer
				$opera = Get-Process Opera -ErrorAction SilentlyContinue
				if ($opera)
				{
					$speak.Speak("Opera was found running, closing the application gracefully.")
					# try gracefully first
					$opera.CloseMainWindow()
					# kill after five seconds
					Sleep 5
					if (!$opera.HasExited)
					{
						$speak.Speak("Opera was found running, closing.")
						$opera | Stop-Process -Force
					}
				}
				
				
				#Find and close Vivaldi Explorer
				$vivaldi = Get-Process Vivaldi -ErrorAction SilentlyContinue
				if ($vivaldi)
				{
					$speak.Speak("Opera was found running, closing the application gracefully.")
					# try gracefully first
					$vivaldi.CloseMainWindow()
					# kill after five seconds
					Sleep 5
					if (!$vivaldi.HasExited)
					{
						$speak.Speak("Opera was found running, closing.")
						$vivaldi | Stop-Process -Force
					}
				}
				Remove-Variable vivaldi
				Remove-Variable opera
				Remove-Variable ie
				Remove-Variable chrome
				Remove-Variable firefox
				
				$favoritesDirectory = "{0:N2} GB" -f ((Get-ChildItem $source\Favorites | Measure-Object Length -s).sum / 1Gb)
				$richtextbox1.Text += "`n`nSometimes I do not close all the windows, please verify that all browser windows are closed now."
				$richtextbox1.Text += "`n`nFailure to close the browser windows will halt the backup until they are closed."
				$richtextbox1.Text += "`nYou have been warned..."
				$richtextbox1.Text += "####################################################"
				#IE Favorites
				$richtextbox1.Text += "`nInitializing IE Favorites Backup. `nIE Favorites Directory is $favoritesDirectory large."
				Robocopy $source\Favorites $dest\Favorites *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$ProgressBar1.Value = "60"
				#Chrome Bookmarks
				$chromeDirectory = "{0:N2} GB" -f ((Get-ChildItem "$source\AppData\Local\Google\Chrome\User Data\Default" | Measure-Object Length -s).sum / 1Gb)
				$richtextbox1.Text += "`n#############`n"
				$richtextbox1.Text += "`nInitializing Chrome Bookmarks Backup. `nThe Chrome Bookmarks are $chromeDirectory large."
				Robocopy "$source\AppData\Local\Google\Chrome\User Data\Default" "$destAppData\AppData\Local\Google\Chrome\User Data\Default" *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$ProgressBar1.Value = "63"
				#Opera Favorites		
				$operaDirectory = "{0:N2} GB" -f ((Get-ChildItem "$source\AppData\Roaming\Opera Software" | Measure-Object Length -s).sum / 1Gb)
				$richtextbox1.Text += "`n#############`n"
				$richtextbox1.Text += "`nInitializing Opera Favorites Backup. `nThe Opera Favorites Are $operaDirectory Large."
				Robocopy "$source\AppData\Roaming\Opera Software" "$dest\AppData\Roaming\Opera Software" *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$ProgressBar1.Value = "64"
				#Vivaldi Favorites		
				$operaDirectory = "{0:N2} GB" -f ((Get-ChildItem "$source\AppData\Local\Vivaldi\User Data\Default\Bookmarks" | Measure-Object Length -s).sum / 1Gb)
				$richtextbox1.Text += "`n#############`n"
				$richtextbox1.Text += "`nInitializing Opera Favorites Backup. `nThe Opera Favorites Are $operaDirectory Large."
				Robocopy "$source\AppData\Local\Vivaldi\User Data\Default\Bookmarks" "$dest\AppData\Local\Vivaldi\User Data\Default\Bookmarks" *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$ProgressBar1.Value = "64"
				#Firefox Bookmarks
				$firefoxDirectory = "{0:N2} GB" -f ((Get-ChildItem $source\AppData\Roaming\Mozilla\Firefox\Profiles | Measure-Object Length -s).sum / 1Gb)
				$richtextbox1.Text += "`n#############`n"
				$richtextbox1.Text += "`nInitializing Firefox Bookmarks Backup. `nThe Firefox Bookmarks Are $firefoxDirectory Large."
				Robocopy $source\AppData\Roaming\Mozilla\Firefox\Profiles $dest\AppData\Roaming\Mozilla\Firefox\Profiles *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$richtextbox1.Text += "`n`nIE, FireFox, Opera, Chrome and Vivaldi Bookmark Directories Completed Backing Up."
				$speak.Speak("The Eye E, Fire Fox, Opera, and Chrome Bookmarks Directories Completed Backing Up. Continuing backup.")
				$richtextbox1.Text += "`n####################################################"
				$ProgressBar1.Value = "65"
			}
			If ($checkboxPictures.Checked)
			{
				#Pictures Directory
				$picturesDirectory = "{0:N2} GB" -f ((Get-ChildItem $source\Pictures | Measure-Object Length -s).sum / 1Gb)
				$richtextbox1.Text += "`nInitializing Pictures Directory Backup. This directory is $picturesDirectory large."
				$speak.Speak("Backing up the Pictures Directory")
				Robocopy $source\Pictures $dest\Pictures *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$picturesDirectory2 = "{0:N2} GB" -f ((Get-ChildItem $dest\Pictures | Measure-Object Length -s).sum / 1Gb)
				if ($picturesDirectory -eq $picturesDirectory2)
				{
					$richtextbox1.Text += "`nPictures Directory Completed Backing Up."
					$speak.Speak("The Pictures Directory Completed Backing Up. Continuing backup.")
					$richtextbox1.Text += "`n###################`n"
					$ProgressBar1.Value = "75"
				}
					else
					{
						$speak.Speak("Source and Destination Directories Do Not Match, Please Check Logs!")
						$result = [System.Windows.Forms.MessageBox]::Show('Pictures Directory Source and Destination Directories Do Not Match, Please Check Logs!', 'Warning', 'YesNo', 'Warning')
						$result
					}
			}
			If ($checkboxVideos.Checked)
				#Videos Directory
				{
					$videoDirectory = "{0:N2} GB" -f ((Get-ChildItem $source\Videos | Measure-Object Length -s).sum / 1Gb)
					$richtextbox1.Text += "`nInitializing Video Directory Backup. "
					$richtextbox1.Text += "`nThis directory is $videoDirectory large."
					$speak.Speak("Backing up the Video Directory")
					Robocopy $source\Videos $dest\Videos *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
					$videoDirectory2 = "{0:N2} GB" -f ((Get-ChildItem $dest\Videos | Measure-Object Length -s).sum / 1Gb)
					if ($videoDirectory -eq $videoDirectory2)
					{
						$richtextbox1.Text += "`nVideos Directory Completed Backing Up."
						$speak.Speak("The Videos Directory Completed Backing Up. Continuing backup.")
						$richtextbox1.Text += "`n#############`n"
						$ProgressBar1.Value = "80"
					}
						else
						{
							$speak.Speak("Source and Destination Directories Do Not Match, Please Check Logs!")
							$result = [System.Windows.Forms.MessageBox]::Show('Video Directory Source and Destination Directories Do Not Match, Please Check Logs!', 'Warning', 'YesNo', 'Warning')
							$result
						}
				}
			If ($checkboxQuickparts.Checked)
			{
				#Office Quick Parts
				$richtextbox1.Text += "`nInitializing Quick Parts Backup."
				Robocopy "$source\application data\microsoft\templates" "$dest\application data\microsoft\templates" *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$richtextbox1.Text += "`nQuickParts Directory Completed Backing Up."
				$speak.Speak("The Microsoft QuickParts Completed Backing Up. Continuing backup.")
				$richtextbox1.Text += "`n#############`n"
				$ProgressBar1.Value = "90"
				
			}
			If ($checkboxCustomDirectory.Checked)
			{
				#Custom Directory 
				$source1 = $textbox7.Text
				$customDirectory = "{0:N2} GB" -f ((Get-ChildItem $source1 | Measure-Object Length -s).sum / 1Gb)
				$richtextbox1.Text += "`nInitializing Custom Directory Backup. "
				$richtextbox1.Text += "`nThe $source1 Directory is $customDirectory Large."
				$richtextbox1.Text += "`nBacking up Directory $source1"
				Robocopy $source1 $dest\Custom_Directory_Backup *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$customDirectory2 = "{0:N2} GB" -f ((Get-ChildItem $dest\Custom_Directory_Backup | Measure-Object Length -s).sum / 1Gb)
				if ($customDirectory -eq $customDirectory2)
				{
					$richtextbox1.Text += "`n$source1 Directory Completed Backing Up to $dest\Custom_Directory_Backup."
					$speak.Speak("The custom backup Directory Completed Backing Up. Continuing backup.")
					$richtextbox1.Text += "`n#############`n"
					$ProgressBar1.Value = "93"
				}
				else
				{
					$speak.Speak("Source and Destination Directories Do Not Match, Please Check Logs!")
					$result = [System.Windows.Forms.MessageBox]::Show('Custom Directory Source and Destination Directories Do Not Match, Please Check Logs!', 'Warning', 'YesNo', 'Warning')
					$result
				}
			}
			If ($checkboxOneDrive.Checked)
			{
				#OneDrive Backup
				$richtextbox1.Text += "`nInitializing OneDrive Directory Backup."
				Robocopy $source\OneDrive - Embry-Riddle Aeronautical University $dest\OneDrive - Embry-Riddle Aeronautical University.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$richtextbox1.Text += "`nOneDrive Directory Completed Backing Up."
				$speak.Speak("The OneDrive, Directory Completed Backing Up. 95 percent complete")
				$richtextbox1.Text += "`n#############`n"
				$ProgressBar1.Value = "95"
			}
			If ($checkboxAdobeSignatureSecuri.Checked)
			{
				#Adobe Signature 
				$richtextbox1.Text += "`nInitializing Adobe Signature/Security Directory Backup."
				Robocopy $source\AppData\Roaming\Adobe\Acrobat\DC\Security $dest\AppData\Roaming\Adobe\Acrobat\DC\Security *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$richtextbox1.Text += "`nAdobe Signature/security Directory Completed Backing Up."
				$richtextbox1.Text += "`n#############`n"
				$speak.Speak("The Adobe signature file Completed Backing Up.")
			}
			If ($checkboxOutlookSignature.Checked)
			{
				#Outlook Signature
				$richtextbox1.Text += "`nInitializing Outlook Signature Directory Backup."
				Robocopy $source\application data\microsoft\signatures $dest\application data\microsoft\signatures *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$richtextbox1.Text += "`nOutlook Signature Completed Backing Up."
				$speak.Speak("The Outlook signatureCompleted Backing Up. 96 percent complete")
				$richtextbox1.Text += "`n#############`n"
				$ProgressBar1.Value = "96"
			}
			If ($checkboxOutlookSettings.Checked)
			{
				#Find and close Oulook Client
				$outlook = Get-Process Outlook -ErrorAction SilentlyContinue
				if ($outlook)
				{
					$speak.Speak("Outlook was found running, closing the application gracefully.")
					# try gracefully first
					$outlook.CloseMainWindow()
					# kill after five seconds
					Sleep 5
					if (!$outlook.HasExited)
					{
						$speak.Speak("Opera was found running, closing.")
						$outlook | Stop-Process -Force
					}
				}
				
				#Outlook 2016 Settings Export
				#cmd /c "REG EXPORT 'HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Outlook' '$dest\Outlook16-config.reg' /y"
				#REG EXPORT 'HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Outlook' '$dest\Outlook16-config.reg' /y
				#Outlook 2013 Settings Export
				#cmd /c "REG EXPORT 'HKEY_CURRENT_USER\​Software\​Microsoft\​Office\​15.0\​Outlook' '$dest\Outlook13-config.reg' /y"
				#REG EXPORT 'HKEY_CURRENT_USER\​Software\​Microsoft\​Office\​15.0\​Outlook' '$dest\Outlook13-config.reg' /y
				#$richtextbox1.Text += "`nOutlook configuration backed up to $dest\Outlook-config.reg."
				#$speak.Speak("Outlook configuration backed up to $dest\Outlook-config.reg. 97 percent complete")
				#$richtextbox1.Text += "`n#############`n"
				#$ProgressBar1.Value = "97"
				Robocopy $source\AppData\Local\Microsoft\Outlook $dest\AppData\Local\Microsoft\Outlook *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$richtextbox1.Text += "`nOutlook settings backed up to $dest\AppData\Local\Microsoft\Outlook."
				$speak.Speak("Outlook settings backed up. 98 percent complete.")
			}
			If ($checkboxOfficeRibbonAndQAT.Checked)
			{
				#The Ribbon and QAT settings in Outlook 2010, Outlook 2013 and Outlook 2016 are stored in officeUI-files in the following folder
				Robocopy $source\AppData\Local\Microsoft\Office $dest\AppData\Local\Microsoft\Office *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$richtextbox1.Text += "`nThe Ribbon and QAT settings in Outlook have been backed up."
				$speak.Speak("The Ribbon and QAT settings in Outlook have been backed up. 99 percent complete.")
				$richtextbox1.Text += "`n#############`n"
			}
			If ($checkboxStickyNotes.Checked)
			{
				#Sticky Notes
				$richtextbox1.Text += "`nInitializing Sticky Notes Directory Backup."
				Robocopy $source\AppData\Local\Packages\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe\LocalState $dest\AppData\Local\Packages\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe\LocalState *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$richtextbox1.Text += "`nStickey Notes Directory Backup Completed.."
				$speak.Speak("Stickey Notes Directory Completed Backing Up.")
				$richtextbox1.Text += "`n#############`n"
			}
			If ($checkboxOneNote2016.Checked)
			{
				#OneNote 2016
				$richtextbox1.Text += "`nInitializing OneNote 2016 Directory Backup."
				Robocopy $source\AppData\Local\Microsoft\OneNote\version\Backup $dest\AppData\Local\Microsoft\OneNote\version\Backup *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
				$richtextbox1.Text += "`nOneNote 2016 Directory Backup Completed.."
				$speak.Speak("One Note 2016 Directory Completed Backing Up.")
				$richtextbox1.Text += "`n#############`n"
			}
			
			#Onedrive not sync'd files
			$richtextbox1.Text += "`nInitializing OneDrive-Not-Yet-Syncd-Files Directory Backup."
			Robocopy $source\ODBA $dest\ODBA *.* /E /ZB /J /LOG+:$source\desktop\backuplog.txt
			$richtextbox1.Text += "`nOneDrive-Not-Yet-Syncd-Files Directory Completed Backing Up."
			$speak.Speak("OneDrive Not Yet Sinked Files Directory Completed Backing Up. 99 point 99 percent complete.")
			$richtextbox1.Text += "`n#############`n"
	
			$ProgressBar1.Value = "100"
			$richtextbox1.Text += "`nPlease check the log file for verification of file transfers. Located: $source\desktop\backuplog.txt."
			$speak.Speak("All selected directories Completed Backing Up. ")
			$richtextbox1.Text += "`nDon't forget to grab all printers, and inventory off the old computer before shutting it down."
			$end = Get-Date
			$statusbar1.Text += "Completed BackUp.. Written by: Alan Newingham."
			$richtextbox1.Text += "`nCompleted Backup at: $end"
			control printers
			$statusbar1.Visible = $true
			Start-Sleep -Seconds 15
			$statusbar1.Visible = $false
			$result = [System.Windows.Forms.MessageBox]::Show('This Operation Completed Successfully!', 'Warning', 'OK', 'Warning')
			$result
			Copy-Item "$source\desktop\backuplog.txt" -Destination "$dest\Logs"
		}
		Else
		{
			$speak.Speak("No joy. I was unable to locate the directory you specified. Please check your path and try again.")
			$result = [System.Windows.Forms.MessageBox]::Show('Unable to reach souce location!', 'Warning', 'YesNo', 'Warning')
			$result
		}
	}
	$buttonBACKUP_Click = {
		
		backupDirectory
	}
	
	$buttonPrograms_Click={
		Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Out-GridView
	}
	
	$buttonPrinters_Click={
		control printers
		Get-Printers
	}
	
	$buttonInventory_Click={
		Get-PSInventory
	}
	
	$buttonCopyToClipboard_Click={
		#TODO: Place custom script here
		$copyText = $richtextbox1.Text
		
		[System.Windows.Forms.Clipboard]::SetText($copyText)
		
		if ([System.Windows.Forms.Clipboard]::ContainsText() -AND
			[System.Windows.Forms.Clipboard]::GetText() -eq $copyText)
		{
			$statusbar1.Text = "Copied to clipboard."
			$statusbar1.Visible = $true
			Start-Sleep -Seconds 2
			$statusbar1.Visible = $false
		}
	}
	
	$richtextbox1_TextChanged = {
		$richtextbox1.SelectionStart = $richtextbox1.TextLength;
		$richtextbox1.ScrollToCaret()
		$richtextbox1.Focus()
	}
	
	$checkboxSelectAll_CheckedChanged={
			$checkboxOneNote2016.Checked = $true
			$checkboxStickyNotes.Checked = $true
			$checkboxOfficeRibbonAndQAT.Checked = $true
			$checkboxOutlookSettings.Checked = $true
			$checkboxOutlookSignature.Checked = $true
			$checkboxAdobeSignatureSecuri.Checked = $true
			$checkboxOneDrive.Checked = $true
			$checkboxCustomDirectory.Checked = $true
			$checkboxBrowsers.Checked = $true
			$checkboxQuickparts.Checked = $true
			$checkboxVideos.Checked = $true
			$checkboxPictures.Checked = $true
			$checkboxDownloads.Checked = $true
			$checkboxDocuments.Checked = $true
			$checkboxDesktop.Checked = $true
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formProfileBackup011ByAl.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonCopyToClipboard.remove_Click($buttonCopyToClipboard_Click)
			$buttonPrograms.remove_Click($buttonPrograms_Click)
			$checkboxSelectAll.remove_CheckedChanged($checkboxSelectAll_CheckedChanged)
			$buttonInventory.remove_Click($buttonInventory_Click)
			$buttonBACKUP.remove_Click($buttonBACKUP_Click)
			$buttonPrinters.remove_Click($buttonPrinters_Click)
			$richtextbox1.remove_TextChanged($richtextbox1_TextChanged)
			$formProfileBackup011ByAl.remove_Load($formProfileBackup011ByAl_Load)
			$formProfileBackup011ByAl.remove_Load($Form_StateCorrection_Load)
			$formProfileBackup011ByAl.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formProfileBackup011ByAl.SuspendLayout()
	$Info.SuspendLayout()
	$groupbox3.SuspendLayout()
	$groupbox2.SuspendLayout()
	#
	# formProfileBackup011ByAl
	#
	$formProfileBackup011ByAl.Controls.Add($statusbar1)
	$formProfileBackup011ByAl.Controls.Add($buttonCopyToClipboard)
	$formProfileBackup011ByAl.Controls.Add($labelLog)
	$formProfileBackup011ByAl.Controls.Add($labelCheckDirectoryYouWan)
	$formProfileBackup011ByAl.Controls.Add($Info)
	$formProfileBackup011ByAl.Controls.Add($buttonPrograms)
	$formProfileBackup011ByAl.Controls.Add($progressbar1)
	$formProfileBackup011ByAl.Controls.Add($groupbox3)
	$formProfileBackup011ByAl.Controls.Add($buttonInventory)
	$formProfileBackup011ByAl.Controls.Add($groupbox2)
	$formProfileBackup011ByAl.Controls.Add($buttonBACKUP)
	$formProfileBackup011ByAl.Controls.Add($buttonPrinters)
	$formProfileBackup011ByAl.Controls.Add($richtextbox1)
	$formProfileBackup011ByAl.AutoScaleDimensions = '6, 13'
	$formProfileBackup011ByAl.AutoScaleMode = 'Font'
	$formProfileBackup011ByAl.ClientSize = '711, 557'
	$formProfileBackup011ByAl.Name = 'formProfileBackup011ByAl'
	$formProfileBackup011ByAl.Text = 'Profile Backup 0.1.1 - By: Alan Newingham'
	$formProfileBackup011ByAl.add_Load($formProfileBackup011ByAl_Load)
	#
	# statusbar1
	#
	$statusbar1.Location = '0, 535'
	$statusbar1.Name = 'statusbar1'
	$statusbar1.Size = '711, 22'
	$statusbar1.TabIndex = 50
	#
	# buttonCopyToClipboard
	#
	$buttonCopyToClipboard.BackColor = 'MenuHighlight'
	$buttonCopyToClipboard.Font = 'Arial, 9.75pt, style=Bold'
	$buttonCopyToClipboard.Location = '359, 484'
	$buttonCopyToClipboard.Name = 'buttonCopyToClipboard'
	$buttonCopyToClipboard.Size = '89, 45'
	$buttonCopyToClipboard.TabIndex = 49
	$buttonCopyToClipboard.Text = 'Copy to Clipboard'
	$buttonCopyToClipboard.UseCompatibleTextRendering = $True
	$buttonCopyToClipboard.UseVisualStyleBackColor = $False
	$buttonCopyToClipboard.add_Click($buttonCopyToClipboard_Click)
	#
	# labelLog
	#
	$labelLog.AutoSize = $True
	$labelLog.Location = '276, 34'
	$labelLog.Name = 'labelLog'
	$labelLog.Size = '26, 17'
	$labelLog.TabIndex = 47
	$labelLog.Text = 'Log:'
	$labelLog.UseCompatibleTextRendering = $True
	#
	# labelCheckDirectoryYouWan
	#
	$labelCheckDirectoryYouWan.AutoSize = $True
	$labelCheckDirectoryYouWan.Location = '270, 54'
	$labelCheckDirectoryYouWan.Name = 'labelCheckDirectoryYouWan'
	$labelCheckDirectoryYouWan.Size = '0, 16'
	$labelCheckDirectoryYouWan.TabIndex = 46
	$labelCheckDirectoryYouWan.UseCompatibleTextRendering = $True
	#
	# Info
	#
	$Info.Controls.Add($labelenvUserName)
	$Info.Controls.Add($labelVer)
	$Info.Controls.Add($labelOSInstallDate)
	$Info.Controls.Add($labeloperatingSystemID)
	$Info.Controls.Add($labelenvCOMPUTERNAME)
	$Info.Controls.Add($labeloperatingSystemNumbe)
	$Info.Controls.Add($labelAuthenticatedUser)
	$Info.Controls.Add($labelInstDate)
	$Info.Controls.Add($labelWindowsUser)
	$Info.Controls.Add($label1)
	$Info.Controls.Add($labelDeviceName)
	$Info.Location = '11, 425'
	$Info.Name = 'Info'
	$Info.Size = '246, 104'
	$Info.TabIndex = 44
	$Info.TabStop = $False
	$Info.Text = 'Information'
	$Info.UseCompatibleTextRendering = $True
	#
	# labelenvUserName
	#
	$labelenvUserName.AutoSize = $True
	$labelenvUserName.Location = '118, 50'
	$labelenvUserName.Name = 'labelenvUserName'
	$labelenvUserName.Size = '86, 17'
	$labelenvUserName.TabIndex = 36
	$labelenvUserName.Text = "$env:UserName"
	$labelenvUserName.UseCompatibleTextRendering = $True
	#
	# labelVer
	#
	$labelVer.AutoSize = $True
	$labelVer.Location = '177, 84'
	$labelVer.Name = 'labelVer'
	$labelVer.Size = '25, 17'
	$labelVer.TabIndex = 53
	$labelVer.Text = 'Ver:'
	$labelVer.UseCompatibleTextRendering = $True
	#
	# labelOSInstallDate
	#
	$labelOSInstallDate.AutoSize = $True
	$labelOSInstallDate.Location = '29, 67'
	$labelOSInstallDate.Name = 'labelOSInstallDate'
	$labelOSInstallDate.Size = '83, 17'
	$labelOSInstallDate.TabIndex = 43
	$labelOSInstallDate.Text = 'OS Install Date:'
	$labelOSInstallDate.UseCompatibleTextRendering = $True
	#
	# labeloperatingSystemID
	#
	$labeloperatingSystemID.AutoSize = $True
	$labeloperatingSystemID.Location = '210, 84'
	$labeloperatingSystemID.Name = 'labeloperatingSystemID'
	$labeloperatingSystemID.Size = '107, 17'
	$labeloperatingSystemID.TabIndex = 52
	$labeloperatingSystemID.Text = "$operatingSystemID"
	$labeloperatingSystemID.UseCompatibleTextRendering = $True
	#
	# labelenvCOMPUTERNAME
	#
	$labelenvCOMPUTERNAME.AutoSize = $True
	$labelenvCOMPUTERNAME.Location = '118, 33'
	$labelenvCOMPUTERNAME.Name = 'labelenvCOMPUTERNAME'
	$labelenvCOMPUTERNAME.Size = '87, 17'
	$labelenvCOMPUTERNAME.TabIndex = 35
	$labelenvCOMPUTERNAME.Text = "$LoggedOnUser"
	$labelenvCOMPUTERNAME.UseCompatibleTextRendering = $True
	#
	# labeloperatingSystemNumbe
	#
	$labeloperatingSystemNumbe.AutoSize = $True
	$labeloperatingSystemNumbe.Location = '8, 84'
	$labeloperatingSystemNumbe.Name = 'labeloperatingSystemNumbe'
	$labeloperatingSystemNumbe.Size = '136, 17'
	$labeloperatingSystemNumbe.TabIndex = 51
	$labeloperatingSystemNumbe.Text = "$operatingSystemNumber"
	$labeloperatingSystemNumbe.UseCompatibleTextRendering = $True
	#
	# labelAuthenticatedUser
	#
	$labelAuthenticatedUser.AutoSize = $True
	$labelAuthenticatedUser.Location = '11, 50'
	$labelAuthenticatedUser.Name = 'labelAuthenticatedUser'
	$labelAuthenticatedUser.Size = '104, 17'
	$labelAuthenticatedUser.TabIndex = 42
	$labelAuthenticatedUser.Text = 'Authenticated User:'
	$labelAuthenticatedUser.UseCompatibleTextRendering = $True
	#
	# labelInstDate
	#
	$labelInstDate.AutoSize = $True
	$labelInstDate.Location = '118, 67'
	$labelInstDate.Name = 'labelInstDate'
	$labelInstDate.Size = '53, 17'
	$labelInstDate.TabIndex = 37
	$labelInstDate.Text = "$InstDate"
	$labelInstDate.UseCompatibleTextRendering = $True
	#
	# labelWindowsUser
	#
	$labelWindowsUser.AutoSize = $True
	$labelWindowsUser.Location = '32, 33'
	$labelWindowsUser.Name = 'labelWindowsUser'
	$labelWindowsUser.Size = '80, 17'
	$labelWindowsUser.TabIndex = 41
	$labelWindowsUser.Text = 'Windows User:'
	$labelWindowsUser.UseCompatibleTextRendering = $True
	#
	# label1
	#
	$label1.AutoSize = $True
	$label1.Location = '118, 16'
	$label1.Name = 'label1'
	$label1.Size = '112, 17'
	$label1.TabIndex = 39
	$label1.Text = "$env:ComputerName"
	$label1.UseCompatibleTextRendering = $True
	#
	# labelDeviceName
	#
	$labelDeviceName.AutoSize = $True
	$labelDeviceName.Location = '38, 15'
	$labelDeviceName.Name = 'labelDeviceName'
	$labelDeviceName.Size = '75, 17'
	$labelDeviceName.TabIndex = 40
	$labelDeviceName.Text = 'Device Name:'
	$labelDeviceName.UseCompatibleTextRendering = $True
	#
	# buttonPrograms
	#
	$buttonPrograms.BackColor = 'MenuHighlight'
	$buttonPrograms.Font = 'Arial, 9.75pt, style=Bold'
	$buttonPrograms.Location = '454, 484'
	$buttonPrograms.Name = 'buttonPrograms'
	$buttonPrograms.Size = '85, 45'
	$buttonPrograms.TabIndex = 34
	$buttonPrograms.Text = 'Programs'
	$buttonPrograms.UseCompatibleTextRendering = $True
	$buttonPrograms.UseVisualStyleBackColor = $False
	$buttonPrograms.add_Click($buttonPrograms_Click)
	#
	# progressbar1
	#
	$progressbar1.Location = '276, 458'
	$progressbar1.Name = 'progressbar1'
	$progressbar1.Size = '429, 22'
	$progressbar1.TabIndex = 30
	#
	# groupbox3
	#
	$groupbox3.Controls.Add($checkboxSelectAll)
	$groupbox3.Controls.Add($checkboxOneNote2016)
	$groupbox3.Controls.Add($checkboxStickyNotes)
	$groupbox3.Controls.Add($checkboxAdobeSignatureSecuri)
	$groupbox3.Controls.Add($checkboxOfficeRibbonAndQAT)
	$groupbox3.Controls.Add($checkboxOutlookSettings)
	$groupbox3.Controls.Add($checkboxOutlookSignature)
	$groupbox3.Controls.Add($checkboxOneDrive)
	$groupbox3.Controls.Add($checkboxCustomDirectory)
	$groupbox3.Controls.Add($textbox7)
	$groupbox3.Controls.Add($checkboxQuickparts)
	$groupbox3.Controls.Add($checkboxBrowsers)
	$groupbox3.Controls.Add($checkboxVideos)
	$groupbox3.Controls.Add($checkboxPictures)
	$groupbox3.Controls.Add($checkboxDocuments)
	$groupbox3.Controls.Add($checkboxDownloads)
	$groupbox3.Controls.Add($checkboxDesktop)
	$groupbox3.Location = '13, 91'
	$groupbox3.Name = 'groupbox3'
	$groupbox3.Size = '246, 328'
	$groupbox3.TabIndex = 29
	$groupbox3.TabStop = $False
	$groupbox3.Text = 'Directories'
	$groupbox3.UseCompatibleTextRendering = $True
	#
	# checkboxSelectAll
	#
	$checkboxSelectAll.Location = '164, 19'
	$checkboxSelectAll.Name = 'checkboxSelectAll'
	$checkboxSelectAll.Size = '76, 24'
	$checkboxSelectAll.TabIndex = 44
	$checkboxSelectAll.Text = 'Select All'
	$checkboxSelectAll.UseCompatibleTextRendering = $True
	$checkboxSelectAll.UseVisualStyleBackColor = $True
	$checkboxSelectAll.add_CheckedChanged($checkboxSelectAll_CheckedChanged)
	#
	# checkboxOneNote2016
	#
	$checkboxOneNote2016.Location = '6, 157'
	$checkboxOneNote2016.Name = 'checkboxOneNote2016'
	$checkboxOneNote2016.Size = '122, 14'
	$checkboxOneNote2016.TabIndex = 43
	$checkboxOneNote2016.Text = 'OneNote 2016'
	$checkboxOneNote2016.UseCompatibleTextRendering = $True
	$checkboxOneNote2016.UseVisualStyleBackColor = $True
	#
	# checkboxStickyNotes
	#
	$checkboxStickyNotes.Location = '6, 251'
	$checkboxStickyNotes.Name = 'checkboxStickyNotes'
	$checkboxStickyNotes.Size = '122, 24'
	$checkboxStickyNotes.TabIndex = 42
	$checkboxStickyNotes.Text = 'Sticky Notes'
	$checkboxStickyNotes.UseCompatibleTextRendering = $True
	$checkboxStickyNotes.UseVisualStyleBackColor = $True
	#
	# checkboxAdobeSignatureSecuri
	#
	$checkboxAdobeSignatureSecuri.Location = '6, 229'
	$checkboxAdobeSignatureSecuri.Name = 'checkboxAdobeSignatureSecuri'
	$checkboxAdobeSignatureSecuri.Size = '164, 24'
	$checkboxAdobeSignatureSecuri.TabIndex = 41
	$checkboxAdobeSignatureSecuri.Text = 'Adobe Signature/Security'
	$checkboxAdobeSignatureSecuri.UseCompatibleTextRendering = $True
	$checkboxAdobeSignatureSecuri.UseVisualStyleBackColor = $True
	#
	# checkboxOfficeRibbonAndQAT
	#
	$checkboxOfficeRibbonAndQAT.Location = '6, 173'
	$checkboxOfficeRibbonAndQAT.Name = 'checkboxOfficeRibbonAndQAT'
	$checkboxOfficeRibbonAndQAT.Size = '152, 21'
	$checkboxOfficeRibbonAndQAT.TabIndex = 40
	$checkboxOfficeRibbonAndQAT.Text = 'Office Ribbon and QAT'
	$checkboxOfficeRibbonAndQAT.UseCompatibleTextRendering = $True
	$checkboxOfficeRibbonAndQAT.UseVisualStyleBackColor = $True
	#
	# checkboxOutlookSettings
	#
	$checkboxOutlookSettings.Location = '6, 190'
	$checkboxOutlookSettings.Name = 'checkboxOutlookSettings'
	$checkboxOutlookSettings.Size = '106, 24'
	$checkboxOutlookSettings.TabIndex = 39
	$checkboxOutlookSettings.Text = 'Outlook Settings'
	$checkboxOutlookSettings.UseCompatibleTextRendering = $True
	$checkboxOutlookSettings.UseVisualStyleBackColor = $True
	#
	# checkboxOutlookSignature
	#
	$checkboxOutlookSignature.Location = '6, 209'
	$checkboxOutlookSignature.Name = 'checkboxOutlookSignature'
	$checkboxOutlookSignature.Size = '122, 24'
	$checkboxOutlookSignature.TabIndex = 38
	$checkboxOutlookSignature.Text = 'Outlook Signature'
	$checkboxOutlookSignature.UseCompatibleTextRendering = $True
	$checkboxOutlookSignature.UseVisualStyleBackColor = $True
	#
	# checkboxOneDrive
	#
	$checkboxOneDrive.Location = '6, 273'
	$checkboxOneDrive.Name = 'checkboxOneDrive'
	$checkboxOneDrive.Size = '104, 24'
	$checkboxOneDrive.TabIndex = 37
	$checkboxOneDrive.Text = 'OneDrive'
	$checkboxOneDrive.UseCompatibleTextRendering = $True
	$checkboxOneDrive.UseVisualStyleBackColor = $True
	#
	# checkboxCustomDirectory
	#
	$checkboxCustomDirectory.Location = '6, 295'
	$checkboxCustomDirectory.Name = 'checkboxCustomDirectory'
	$checkboxCustomDirectory.Size = '122, 24'
	$checkboxCustomDirectory.TabIndex = 36
	$checkboxCustomDirectory.TabStop = $False
	$checkboxCustomDirectory.Text = 'Custom Directory'
	$checkboxCustomDirectory.UseCompatibleTextRendering = $True
	$checkboxCustomDirectory.UseVisualStyleBackColor = $True
	#
	# textbox7
	#
	$textbox7.Location = '129, 295'
	$textbox7.Name = 'textbox7'
	$textbox7.Size = '100, 20'
	$textbox7.TabIndex = 35
	#
	# checkboxQuickparts
	#
	$checkboxQuickparts.Location = '6, 76'
	$checkboxQuickparts.Name = 'checkboxQuickparts'
	$checkboxQuickparts.Size = '109, 24'
	$checkboxQuickparts.TabIndex = 34
	$checkboxQuickparts.Text = 'Quickparts'
	$checkboxQuickparts.UseCompatibleTextRendering = $True
	$checkboxQuickparts.UseVisualStyleBackColor = $True
	#
	# checkboxBrowsers
	#
	$checkboxBrowsers.Location = '6, 134'
	$checkboxBrowsers.Name = 'checkboxBrowsers'
	$checkboxBrowsers.Size = '104, 24'
	$checkboxBrowsers.TabIndex = 33
	$checkboxBrowsers.Text = 'Browsers'
	$checkboxBrowsers.UseCompatibleTextRendering = $True
	$checkboxBrowsers.UseVisualStyleBackColor = $True
	#
	# checkboxVideos
	#
	$checkboxVideos.Location = '6, 57'
	$checkboxVideos.Name = 'checkboxVideos'
	$checkboxVideos.Size = '104, 24'
	$checkboxVideos.TabIndex = 32
	$checkboxVideos.Text = 'Videos'
	$checkboxVideos.UseCompatibleTextRendering = $True
	$checkboxVideos.UseVisualStyleBackColor = $True
	#
	# checkboxPictures
	#
	$checkboxPictures.Location = '6, 115'
	$checkboxPictures.Name = 'checkboxPictures'
	$checkboxPictures.Size = '104, 24'
	$checkboxPictures.TabIndex = 31
	$checkboxPictures.Text = 'Pictures'
	$checkboxPictures.UseCompatibleTextRendering = $True
	$checkboxPictures.UseVisualStyleBackColor = $True
	#
	# checkboxDocuments
	#
	$checkboxDocuments.Location = '6, 96'
	$checkboxDocuments.Name = 'checkboxDocuments'
	$checkboxDocuments.Size = '104, 24'
	$checkboxDocuments.TabIndex = 30
	$checkboxDocuments.Text = 'Documents'
	$checkboxDocuments.UseCompatibleTextRendering = $True
	$checkboxDocuments.UseVisualStyleBackColor = $True
	#
	# checkboxDownloads
	#
	$checkboxDownloads.Location = '6, 38'
	$checkboxDownloads.Name = 'checkboxDownloads'
	$checkboxDownloads.Size = '104, 24'
	$checkboxDownloads.TabIndex = 29
	$checkboxDownloads.Text = 'Downloads'
	$checkboxDownloads.UseCompatibleTextRendering = $True
	$checkboxDownloads.UseVisualStyleBackColor = $True
	#
	# checkboxDesktop
	#
	$checkboxDesktop.Location = '6, 19'
	$checkboxDesktop.Name = 'checkboxDesktop'
	$checkboxDesktop.Size = '104, 27'
	$checkboxDesktop.TabIndex = 28
	$checkboxDesktop.Text = 'Desktop'
	$checkboxDesktop.UseCompatibleTextRendering = $True
	$checkboxDesktop.UseVisualStyleBackColor = $True
	#
	# buttonInventory
	#
	$buttonInventory.BackColor = 'MenuHighlight'
	$buttonInventory.Font = 'Arial, 9.75pt, style=Bold'
	$buttonInventory.Location = '630, 484'
	$buttonInventory.Name = 'buttonInventory'
	$buttonInventory.Size = '75, 45'
	$buttonInventory.TabIndex = 33
	$buttonInventory.Text = 'Inventory'
	$buttonInventory.UseCompatibleTextRendering = $True
	$buttonInventory.UseVisualStyleBackColor = $False
	$buttonInventory.add_Click($buttonInventory_Click)
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($textbox1)
	$groupbox2.Controls.Add($textbox2)
	$groupbox2.Controls.Add($labelFromLocation)
	$groupbox2.Controls.Add($labelToLocation)
	$groupbox2.Location = '13, 9'
	$groupbox2.Name = 'groupbox2'
	$groupbox2.Size = '245, 76'
	$groupbox2.TabIndex = 28
	$groupbox2.TabStop = $False
	$groupbox2.Text = 'Locations'
	$groupbox2.UseCompatibleTextRendering = $True
	#
	# textbox1
	#
	$textbox1.Location = '102, 19'
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '128, 20'
	$textbox1.TabIndex = 1
	#
	# textbox2
	#
	$textbox2.Location = '102, 45'
	$textbox2.Name = 'textbox2'
	$textbox2.Size = '128, 20'
	$textbox2.TabIndex = 2
	#
	# labelFromLocation
	#
	$labelFromLocation.AutoSize = $True
	$labelFromLocation.Location = '7, 22'
	$labelFromLocation.Name = 'labelFromLocation'
	$labelFromLocation.Size = '77, 17'
	$labelFromLocation.TabIndex = 11
	$labelFromLocation.Text = 'From Location'
	$labelFromLocation.UseCompatibleTextRendering = $True
	#
	# labelToLocation
	#
	$labelToLocation.AutoSize = $True
	$labelToLocation.Location = '7, 48'
	$labelToLocation.Name = 'labelToLocation'
	$labelToLocation.Size = '63, 17'
	$labelToLocation.TabIndex = 12
	$labelToLocation.Text = 'To Location'
	$labelToLocation.UseCompatibleTextRendering = $True
	#
	# buttonBACKUP
	#
	$buttonBACKUP.BackColor = 'MenuHighlight'
	$buttonBACKUP.Font = 'Arial Black, 9.75pt, style=Bold'
	$buttonBACKUP.ForeColor = 'ControlText'
	$buttonBACKUP.Location = '276, 484'
	$buttonBACKUP.Name = 'buttonBACKUP'
	$buttonBACKUP.Size = '77, 45'
	$buttonBACKUP.TabIndex = 31
	$buttonBACKUP.Text = 'Backup'
	$buttonBACKUP.UseCompatibleTextRendering = $True
	$buttonBACKUP.UseVisualStyleBackColor = $False
	$buttonBACKUP.add_Click($buttonBACKUP_Click)
	#
	# buttonPrinters
	#
	$buttonPrinters.BackColor = 'MenuHighlight'
	$buttonPrinters.Font = 'Arial, 9.75pt, style=Bold'
	$buttonPrinters.Location = '545, 484'
	$buttonPrinters.Name = 'buttonPrinters'
	$buttonPrinters.Size = '79, 45'
	$buttonPrinters.TabIndex = 32
	$buttonPrinters.Text = 'Printers'
	$buttonPrinters.UseCompatibleTextRendering = $True
	$buttonPrinters.UseVisualStyleBackColor = $False
	$buttonPrinters.add_Click($buttonPrinters_Click)
	#
	# richtextbox1
	#
	$richtextbox1.Location = '276, 54'
	$richtextbox1.Name = 'richtextbox1'
	$richtextbox1.Size = '429, 398'
	$richtextbox1.TabIndex = 7
	$richtextbox1.Text = ''
	$richtextbox1.add_TextChanged($richtextbox1_TextChanged)
	#
	# tooltip1
	#
	$groupbox2.ResumeLayout()
	$groupbox3.ResumeLayout()
	$Info.ResumeLayout()
	$formProfileBackup011ByAl.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formProfileBackup011ByAl.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formProfileBackup011ByAl.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formProfileBackup011ByAl.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formProfileBackup011ByAl.ShowDialog()

} #End Function

#Call the form
Show-ProfileBackup | Out-Null

		
		